// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package com.sunpe.grpc_with_consul.server.proto;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();
}
