// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health.proto

package com.sunpe.grpc_with_consul.server.proto;

public final class HealthOuterClass {
  private HealthOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014health.proto\022\016grpc.health.v1\"%\n\022Health" +
      "CheckRequest\022\017\n\007service\030\001 \001(\t\"\251\001\n\023Health" +
      "CheckResponse\022A\n\006status\030\001 \001(\01621.grpc.hea" +
      "lth.v1.HealthCheckResponse.ServingStatus" +
      "\"O\n\rServingStatus\022\013\n\007UNKNOWN\020\000\022\013\n\007SERVIN" +
      "G\020\001\022\017\n\013NOT_SERVING\020\002\022\023\n\017SERVICE_UNKNOWN\020" +
      "\0032\256\001\n\006Health\022P\n\005Check\022\".grpc.health.v1.H" +
      "ealthCheckRequest\032#.grpc.health.v1.Healt" +
      "hCheckResponse\022R\n\005Watch\022\".grpc.health.v1" +
      ".HealthCheckRequest\032#.grpc.health.v1.Hea" +
      "lthCheckResponse0\001B.\n\'com.sunpe.grpc_wit" +
      "h_consul.server.protoP\001\210\001\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
